### ISSUE TITLE
Process died after roslaunch

### ISSUE THREAD

**Issue by feiyuxiaoThu** [jchengai/gpir#4]
Hi,
when i run _roslaunch planning_core planning.launch_ , the process just died.

log:

> SUMMARY
> ========
> 
> PARAMETERS
>  * /carla_controller/kd: 0.4
>  * /carla_controller/ki: 0.15
>  * /carla_controller/kp: 3.5
>  * /planning/map_path: /home/xfy/catkin_...
>  * /planning/random_drive_mode: True
>  * /planning/simulator: Carla
>  * /planning/town: Town05
>  * /robot_description: <?xml version="1....
>  * /rosdistro: noetic
>  * /rosversion: 1.15.14
> 
> NODES
>   /
>     carla_controller (planning_core/carla_controller)
>     planning (planning_core/planning)
>     planning_rviz (rviz/rviz)
>     vehicle (robot_state_publisher/robot_state_publisher)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[planning-1]: started with pid [26740]
> process[carla_controller-2]: started with pid [26741]
> process[planning_rviz-3]: started with pid [26749]
> process[vehicle-4]: started with pid [26750]
> [2022-07-24 15:12:30.995] [info] ensureValid(::ad::physics::Distance)>> 1.4224e+10 value out of range
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  Distance value out of range
> *** Aborted at 1658646750 (unix time) try "date -d @1658646750" if you are using GNU date ***
> PC: @     0x7f375ad3d00b gsignal
> *** SIGABRT (@0x3e800006874) received by PID 26740 (TID 0x7f375546c980) from PID 26740; stack trace: ***
>     @     0x7f375ad3d090 (unknown)
>     @     0x7f375ad3d00b gsignal
>     @     0x7f375ad1c859 abort
>     @     0x7f375afa5911 (unknown)
>     @     0x7f375afb138c (unknown)
>     @     0x7f375afb13f7 std::terminate()
>     @     0x7f375afb16a9 __cxa_throw
>     @     0x7f375a1691fe ad::physics::Distance::ensureValid()
>     @     0x7f375a1a6f6a ad::map::point::findNearestPointOnEdge<>()
>     @     0x7f375a1a7c3a ad::map::point::findNearestPointOnSegment<>()
>     @     0x7f375a1a8340 ad::map::point::findNearestPointOnEdge<>()
>     @     0x7f375a1a8b4f ad::map::point::calculateWidthRange<>()
>     @     0x7f375a1a4878 ad::map::lane::updateLaneLengths()
>     @     0x7f375a13a3c8 ad::map::access::Factory::set()
>     @     0x7f375a1be8d0 ad::map::opendrive::AdMapFactory::addLane()
>     @     0x7f375a1c00dc ad::map::opendrive::AdMapFactory::convertToAdMap()
>     @     0x7f375a1c0877 ad::map::opendrive::AdMapFactory::createAdMap()
>     @     0x7f375a1c0de0 ad::map::opendrive::AdMapFactory::createAdMap()
>     @     0x7f375a1284b3 ad::map::access::AdMapAccess::readOpenDriveMap()
>     @     0x7f375a129875 ad::map::access::AdMapAccess::initialize()
>     @     0x7f375b3ece0c hdmap::HdMapImpl::LoadMap()
>     @     0x563a8e5be595 planning::PlanningCore::Init()
>     @     0x563a8e5bd4e8 main
>     @     0x7f375ad1e083 __libc_start_main
>     @     0x563a8e5bd63e _start
> [planning-1] process has died

**Comment by jchengai** [comment]
It looks like an internal problem of the ad_map library, and I can't reproduce this problem in my machine.

FYI, my environment:

- os: ubuntu20.04
- ros: neotic
- g++: 9.4.0

**Comment by feiyuxiaoThu** [comment]
I found the main error was caused by the incompatible versions between conda and ubuntu self-installed python, and now I have reproduced the results following the instructions. A nice work and the intuition for  using GP and inference for motion planning is splendid!
