### ISSUE TITLE
Error occured when roslaunch keyboard.launch

### ISSUE THREAD

**Issue by badaolaziang** [jchengai/gpir#8]
Hi, Thank a lot  for open sourcing this great work! 
When attempting to apply this work, I encounter some difficulty and hope to get some suggestions.

When I try **roslaunch planning_core planning.launch**, I get the following:

> SUMMARY
> 
> PARAMETERS
>  * /carla_controller/kd: 0.4
>  * /carla_controller/ki: 0.15
>  * /carla_controller/kp: 3.5
>  * /planning/map_path: /home/luoteng/cat...
>  * /planning/random_drive_mode: True
>  * /planning/simulator: Carla
>  * /planning/town: Town05
>  * /robot_description: <?xml version="1....
>  * /rosdistro: noetic
>  * /rosversion: 1.15.14
> 
> NODES
>   /
>     carla_controller (planning_core/carla_controller)
>     planning (planning_core/planning)
>     planning_rviz (rviz/rviz)
>     vehicle (robot_state_publisher/robot_state_publisher)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[planning-1]: started with pid [644605]
> process[carla_controller-2]: started with pid [644606]
> process[planning_rviz-3]: started with pid [644607]
> process[vehicle-4]: started with pid [644613]
> [pcl::PCDReader::read] Could not find file '/home/luoteng/catkin_gpir/src/gpir/hdmap/maps/pcd/Town05.pcd'.
> Fail to load pcd file: /home/luoteng/catkin_gpir/src/gpir/hdmap/maps/pcd/Town05.pcd
> **W1127 16:04:53.694373 644605 carla_ego_info.cc:87] cannot receive ego info from carla
> W1127 16:04:53.694741 644605 carla_adapter.cc:40] fail to get vehicle param from Carla, Retry: 0**
> I1127 16:04:55.695619 644605 carla_adapter.cc:37] 
> length: 4.79178
> width: 2.16345
> height: 1.48832
> wheel_base: 3.00465
> front_to_front_axle: 0.777641
> back_to_rear_axle: 1.00949
> rear_axle_to_center: 1.3864
> I1127 16:04:55.695652 644605 planning_core.cc:45] Init simulator Carla OK

And when I try **roslaunch planning_core keyboard.launch**, I get the following:

> SUMMARY
> 
> PARAMETERS
>  * /rosdistro: noetic
>  * /rosversion: 1.15.14
> 
> NODES
>   /
>     keyboard (planning_core/keyboard.py)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[keyboard-1]: started with pid [645243]
> pygame 2.1.2 (SDL 2.0.16, Python 3.7.15)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Traceback (most recent call last):
>   File "/home/luoteng/catkin_gpir/src/gpir/planning_core/keyboard.py", line 321, in <module>
>     main()
>   File "/home/luoteng/catkin_gpir/src/gpir/planning_core/keyboard.py", line 307, in main
>     keyboard_handler = KeyboardHandler(args)
>   File "/home/luoteng/catkin_gpir/src/gpir/planning_core/keyboard.py", line 170, in __init__
>     self.agent_generator = AgentGenerator(args)
>   File "/home/luoteng/catkin_gpir/src/gpir/planning_core/keyboard.py", line 53, in __init__
>     self.ego = actors[0]
> IndexError: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
> **[keyboard-1] process has died [pid 645243, exit code 1, cmd /home/luoteng/catkin_gpir/src/gpir/planning_core/keyboard.py --img=/home/luoteng/catkin_gpir/src/gpir/planning_core/keyboard.png __name:=keyboard __log:=/home/luoteng/.ros/log/b1045c60-6a5c-11ed-997a-434582c5cbfd/keyboard-1.log].**
> log file: /home/luoteng/.ros/log/b1045c60-6a5c-11ed-997a-434582c5cbfd/keyboard-1*.log
> all processes on machine have died, roslaunch will exit
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done

I am tring to solve the encountered problem, and I may wonder if there is something I missed that leads to the situation, or someone have met the similar situation. Thanks again for the sharing of the excellent work.

**Comment by jchengai** [comment]
Hi, it looks like the client cannot extract actors from simulator. You may try to comment out the filter in line 51 to see if there is any actor. 

https://github.com/jchengai/gpir/blob/1bed4d500a5df55531379f13a65c5c14d3fef921/planning_core/keyboard.py#L50-L57

**Comment by badaolaziang** [comment]
Thanks for the reply. You are right that I found out that when I **roslaunch planning_core carla_setup.launch**, I get 

> Exception in thread Thread-7:
> Traceback (most recent call last):
>   File "/home/zza/miniconda3/envs/carla_py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "/home/zza/miniconda3/envs/carla_py37/lib/python3.7/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 271, in _synchronous_mode_update
>     self._update(frame, world_snapshot.timestamp.elapsed_seconds)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 312, in _update
>     self.actor_factory.update_actor_states(frame_id, timestamp)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/actor_factory.py", line 143, in update_actor_states
>     self.actors[actor_id].update(frame_id, timestamp)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 253, in update
>     self._update_synchronous_sensor(frame, timestamp)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 234, in _update_synchronous_sensor
>     self.sensor_data_updated(carla_sensor_data)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/camera.py", line 121, in sensor_data_updated
>     img_msg = self.get_ros_image(carla_camera_data)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/camera.py", line 163, in get_ros_image
>     img_msg = Camera.cv_bridge.cv2_to_imgmsg(image_data_array, encoding=encoding)
>   File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 266, in cv2_to_imgmsg
>     if self.cvtype_to_name[self.encoding_to_cvtype2(encoding)] != cv_type:
>   File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 91, in encoding_to_cvtype2
>     from cv_bridge.boost.cv_bridge_boost import getCvType
> ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
> 
> [INFO] [1669715562.487306, 1.901501]: Object (type='sensor.other.lane_invasion', id='lane_invasion') spawned successfully as 247.
> [INFO] [1669715562.489062, 1.901501]: Object (type='sensor.pseudo.tf', id='tf') spawned successfully as 10005.
> [INFO] [1669715562.490352, 1.901501]: Object (type='sensor.pseudo.odom', id='odometry') spawned successfully as 10006.
> [INFO] [1669715562.490864, 1.901501]: All objects spawned.

So it seems that I didnot make the carla_ros_bridge right. I will try to figure it out. Thanks again.
